### ISSUE TITLE
solve on MethodCallExpr will result in StackOverflowError when parameter type inherits from a super class with the same name in a different package

### ISSUE THREAD

**Issue by apeloquin-agilysys** [javaparser/javasymbolsolver#113]
Hello,

We've run across a code (anti-pattern) that is tripping up this library.  The symbol solver does not appear to handle class inheritance where the same name is shared across different packages.  

I put together a small project (attached) to illustrate.  I have a Widget class in com.foo that inherits from a Widget class in com.foo.base.  When trying to solve a MethodCallExpr on a method involving this type, it gets stuck in a recursive loop as the call to JavaParserClassDeclaration.getSuperClass() always returns the current class instead of the actual superclass with the same name.

[javasymbolsolver-issue.tar.gz](https://github.com/javaparser/javasymbolsolver/files/559368/javasymbolsolver-issue.tar.gz)

`package com.foo.base;

public class Widget {}

package com.foo;

public class Widget extends com.foo.base.Widget {

    public static void main(String[] args) throws IOException, ParseException {
        File src = new File(JAVA_ROOT);
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver(true));
        combinedTypeSolver.add(new JavaParserTypeSolver(src));

        CompilationUnit compilationUnit = JavaParser.parse(new File(CLASS));

        JavaParserFacade parserFacade = JavaParserFacade.get(combinedTypeSolver);
        MethodDeclaration methodDeclaration = compilationUnit.getNodesByType(MethodDeclaration.class).stream()
              .filter(node -> node.getName().equals("doSomething")).findAny().orElse(null);
        methodDeclaration.getNodesByType(MethodCallExpr.class).forEach(parserFacade::solve);
    }

    public void doSomething() {
        doSomethingMore(new Widget());
    }

    public void doSomethingMore(Widget value) {
        // does something
    }
`

Results in: 
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.ast.NodeList.iterator(NodeList.java:123)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.methodsByName(ClassOrInterfaceDeclarationContext.java:139)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:152)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:476)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:163)
(last 2 lines repeating)

Thanks,
Aaron

**Comment by ftomassetti** [comment]
Thank you so much for reporting this

**Comment by ftomassetti** [comment]
I have added some tests to verifying this but I could not reproduce it. I think the bug has been corrected in the previous months. I will commit the new tests to prevent regressions.
