### ISSUE TITLE
Uncaught exception, UnsolvedSymbolException(var11) at 473:JavaParserFacade

### ISSUE THREAD

**Issue by MarcialSanchez** [javaparser/javasymbolsolver#12]
First of all, thanks a lot for your work in this amazing tools!. I'm using JavaParser and java-symbol-solver to make an analysis tool.

I'm triying to execute this code:

```
CombinedTypeSolver typeSolver = new CombinedTypeSolver();
typeSolver.add(new JreTypeSolver());
typeSolver.add(new JavaParserTypeSolver(new File("path/to/example/JavaProject")));
TypeUsage typeOfTheNode = JavaParserFacade.get(typeSolver).getType(node);
```

The Node in this example is a MethodCallExpr - "instance.em.createNativeQuery("shutdown").executeUpdate();"  from the source file I'm trying to analyze,  it's located inside the JavaProject path given to JavaParserTypeSolver):

```
package persistence;

import persistence.ExcepcionesPersis.DBConexionError;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class PersistenceManager {

    EntityManagerFactory emf;
    EntityManager em;
    static PersistenceManager instance = null;

    private PersistenceManager() {
        emf = Persistence.createEntityManagerFactory("Example");
        em = emf.createEntityManager();
    }

    public EntityManager getEntityManager() {
        return em;
    }

    public static void newConnection() throws DBConexionError {
        if (instance == null) {
            instance = new PersistenceManager();
        }
    }

    public static PersistenceManager instance() {
        return instance;
    }

    public static void closeConnection() {
        if (instance != null) {
            instance.em.getTransaction().begin();
            instance.em.createNativeQuery("shutdown").executeUpdate();
            instance.em.getTransaction().commit();
            instance.em.close();
            instance.emf.close();
            instance = null;
        }
    }

}
```

And the error I get:

```
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='EntityManager', typeSolver=null}
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:438)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:428)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:481)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:477)
    at me.tomassetti.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration.getType(JavaParserFieldDeclaration.java:37)
    at me.tomassetti.symbolsolver.model.typesystem.ReferenceTypeUsage.getFieldType(ReferenceTypeUsage.java:131)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.FieldAccessContext.solveSymbolAsValue(FieldAccessContext.java:45)
    at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:42)
    at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:47)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:290)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:153)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:494)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:220)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:153)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:494)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:220)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
    at es.ujaen.Searcher$MethodCallVisitor.visit(Searcher.java:89)
    at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:407)
    at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:459)
    at com.github.javaparser.ast.stmt.IfStmt.accept(IfStmt.java:61)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:567)
    at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:113)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:231)
    at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:86)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:260)
    at es.ujaen.Searcher.search(Searcher.java:48)
    at es.ujaen.Searcher.searchReferences(Searcher.java:27)
    at es.ujaen.Engine.run(Engine.java:23)
    at es.ujaen.Main.main(Main.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1
```

This is just an example of what I'm doing, I have tried diferent types of nodes and I always get the same exception.
Am I doing something wrong?

**Comment by ftomassetti** [comment]
Hi Marcial, thank you for your nice words! I hope to hear more about your tool (perhaps we could write a post about it for [my blog](http://tomassetti.me)). This project is quite new and feedback helps me a lot.

I will not be able to test this during the week-end but I think it cannot find EntityManager because it is not part of the JRE/JDK, you need a specific JAR. If you get that JAR you could just add a JarTypeSolver and it should work.

**Comment by MarcialSanchez** [comment]
Thanks for the reply!.

I just remember that the test project I'm using was made with Hibernate, and I need to add the JARs.
Another mistake was that the path I used in JavaParserTypeSolver was the root folder of the project, not the sources folder.

But now I have two more questions:

1- From a node of the type MethodCallExpr I need the qualified name of the method referenced in it. I have find this way to obtain it:

```
MethodUsage solvedMethod = JavaParserFacade.get(typeSolver).solveMethodAsUsage(node);
                String qualifiedName=solvedMethod.declaringType().getQualifiedName()+"."+solvedMethod.getName()+"(";
                for(int i = 0; i<solvedMethod.getParamTypes().size();i++){

                    if(solvedMethod.getParamTypes().size()>1 && i != 0){
                        qualifiedName = qualifiedName.concat(",");
                    }
                    String type = solvedMethod.getParamTypes().get(i).describe();
                    qualifiedName = qualifiedName.concat(type.substring(type.lastIndexOf(".")+1));
                }
                qualifiedName = qualifiedName.concat(")");
```
Any "easy" way to do this?


2-  Now I'm getting this type of Exception when I try to solve any method of an EntityManager or EntityManagerFactory.

· Example code where I'm trying to solve "emf.createEntityManager()" method: 
```
    EntityManagerFactory emf;    // We are using an Interface(EntityManagerFactory) as a Type
    EntityManager em;                 // This type (EntityManager) is also a Interface

    emf = Persistence.createEntityManagerFactory("ExampleName"); // This returns an object of a class that implements the EntityManagerFactory Interface
    em = emf.createEntityManager();  // Same here the returning object is an instance of a class that implements the EntityManagerInterface
```
The exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: 
                            javassist.CtClassType@2d6a9952[changed public abstract interface class javax.persistence.EntityManagerFactory 
                            fields= 
                            constructors= 
                            methods=javassist.CtMethod@fa76482f[public abstract createEntityManager ()Ljavax/persistence/EntityManager;], 
                                    javassist.CtMethod@622ca8b8[public abstract createEntityManager (Ljava/util/Map;)Ljavax/persistence/EntityManager;], 
                                    javassist.CtMethod@33a644f9[public abstract close ()V], javassist.CtMethod@ebf0b295[public abstract isOpen ()Z], 
                                    ]
    at me.tomassetti.symbolsolver.javassistmodel.JavassistClassDeclaration.<init>(JavassistClassDeclaration.java:57)
    at me.tomassetti.symbolsolver.resolution.typesolvers.JarTypeSolver.tryToSolveType(JarTypeSolver.java:112)
    at me.tomassetti.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:40)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:125)
    at me.tomassetti.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveType(JavaParserClassDeclaration.java:333)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:113)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:428)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:481)
    at me.tomassetti.symbolsolver.javaparsermodel.declarations.JavaParserSymbolDeclaration.getType(JavaParserSymbolDeclaration.java:131)
    at me.tomassetti.symbolsolver.model.resolution.Value.from(Value.java:22)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveWithAsValue(AbstractJavaParserContext.java:72)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbolAsValue(ClassOrInterfaceDeclarationContext.java:77)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.ConstructorContext.solveSymbolAsValue(ConstructorContext.java:60)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:66)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:88)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:197)
    at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:42)
    at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:47)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:211)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
    at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:153)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:494)
    at es.ujaen.Searcher$MethodCallVisitor.visit(Searcher.java:151)
    at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:152)
    at com.github.javaparser.ast.expr.AssignExpr.accept(AssignExpr.java:76)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:407)
    at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:297)
    at com.github.javaparser.ast.body.ConstructorDeclaration.accept(ConstructorDeclaration.java:95)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:231)
    at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:86)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:260)
    at es.ujaen.Searcher.search(Searcher.java:70)
    at es.ujaen.Searcher.searchReferences(Searcher.java:35)
    at es.ujaen.Engine.run(Engine.java:23)
    at es.ujaen.Main.main(Main.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Thanks for your time!.

**Comment by ftomassetti** [comment]
Hi @MarcialSanchez 
1) no, there is not currently a single method to call to get the signature of the method, I created an issue for that (#13)
2) it seems that we are trying to create a ClassDeclaration wrapping an interface. It is probably a bug in Java-Symbol-Solver, I will open an issue for that an investigate

Thanks and please ask all the questions you need!
