### ISSUE TITLE
Getting name of unresolved symbol

### ISSUE THREAD

**Issue by bazhenov** [javaparser/javasymbolsolver#121]
Suppose I have following example:

	String code = "package org;\n" +
		"import static org.Foo.foo;\n" +
		"public class A { A() { foo(); } }";
	CompilationUnit compilationUnit = JavaParser.parse(code);

	JavaParserFacade facade = JavaParserFacade.get(new JreTypeSolver());

	compilationUnit.getNodesByType(MethodCallExpr.class).forEach(m -> {
		try {
			SymbolReference<MethodDeclaration> solve = facade.solve(m);
			if (solve.isSolved()) {
				System.out.println(solve.getCorrespondingDeclaration().declaringType().getQualifiedName() + " :: " + m.getName());
			} else {
				System.out.println("Unable to resolve: " + m.getName() + " " + m.getBegin().line);
			}
		} catch (UnsolvedSymbolException e) {
			System.out.println("Unable to resolve: " + m.getName() + " " + m.getBegin().line);
		}
	});

I will get:

	Exception in thread "main" UnsolvedSymbolException{context='null', name='org.Foo', typeSolver=me.tomassetti.symbolsolver.resolution.typesolvers.JreTypeSolver@21588809}
		at me.tomassetti.symbolsolver.model.resolution.TypeSolver.solveType(TypeSolver.java:29)
		at me.tomassetti.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveMethod(CompilationUnitContext.java:190)
		at me.tomassetti.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:179)
		at me.tomassetti.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:463)
		at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:268)
		at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:143)
		at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:118)

Apparently, type was correctly inferred but not resolved as it doesn't exists in `TypeSolver`. Fortunately my application has no need in type resolving. I just need the type name as a string. Is there any way I can get it?

**Comment by ftomassetti** [comment]
In general we need to resolve types in order to resolve symbols. For example, I need the type of an element to understand which methods is called on it. In this case it would try to check if the method `foo` is taking zero parameters, because otherwise you are not really calling `foo`. You are not calling anything. I guess in this case the best you can do is catching the exception.

I will try to think more about this and see if another strategy can be implemented.

In the meantime: thank you very much for providing feedback!

**Comment by bazhenov** [comment]
Seems reasonable. I'm ok with that. The only problem I have – `UnresolvedSymbolException` doesn't have `getName()` and now I forced to parse symbol name using regexp.

Maybe we should put getter for `name` in `UnreasolvedSymbolException`? Current approach is not stable in face of exception message changes.

**Comment by ftomassetti** [comment]
Sure, we will add a getter for the name

**Comment by matozoid** [comment]
Added in 3.6.21
