### ISSUE TITLE
JavaParser version

### ISSUE THREAD

**Issue by crac1017** [javaparser/javasymbolsolver#137]
Hello,

I really love your work on JavaParser and JavaSymbolSolver. I'm wondering what version of JavaParser JavaSymbolSolver is using? I'm asking this question because when I'm using JavaParser 3.0.1 and JavaSymbolSolver 0.4.0, I got an exception:

An exception or error caused a run to abort: com.github.javaparser.ast.stmt.BlockStmt.getStmts()Lcom/github/javaparser/ast/NodeList; 
java.lang.NoSuchMethodError: com.github.javaparser.ast.stmt.BlockStmt.getStmts()Lcom/github/javaparser/ast/NodeList;
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:91)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:66)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:179)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:173)

And I found out that getStmts is called with a BlockStmt object. I remember that getStmts was replaced with getStatements. Is that true? If that's the case, what version of JavaParser should I be using?

Thank you very much.

**Comment by matozoid** [comment]
The miracles of open source software: https://github.com/javaparser/javasymbolsolver/blob/master/java-symbol-solver-core/pom.xml

Looks like it's 3.0.0 :) Maven should automatically get the correct version if you only add JSS as a dependency.

**Comment by ftomassetti** [comment]
@matozoid has replied to this one, closing
