### ISSUE TITLE
please close this

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javasymbolsolver#148]
issue solved

**Comment by ftomassetti** [comment]
Happy that you solve the issue!

**Comment by tamtam22** [comment]
Hi,

Sorry to trouble you to re-open this again. The problem was partially solved but not fully.

Still getting these:

~~~~
UnsolvedSymbolException{context='unknown', name='Button', typeSolver=null}

UnsolvedSymbolException{context='unknown', name='WebViewClient', typeSolver=null}

UnsolvedSymbolException{context='unknown', name='EditText', typeSolver=null}

UnsolvedSymbolException{context='unknown', name='XMLReader', typeSolver=null}
~~~~


And 1 more very weird one:
~~~~
method: proceed
code: request.proceed(MainActivity.this.mPrivateKey, MainActivity.this.mCertificates)

java.lang.RuntimeException: Error calculating the type of parameter MainActivity.this.mPrivateKey of method call request.proceed(MainActivity.this.mPrivateKey, MainActivity.this.mCertificates)
~~~~

**Comment by tamtam22** [comment]
I am thinking that, if a symbol is unresolved, can we use the "name" in : `UnsolvedSymbolException{context='unknown', name='EditText', typeSolver=null}`

and then look into the imports:
~~~~
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Button;
import android.widget.EditText;
~~~~
And if it is there, then that is the symbol to return, in this case, **android.widget.EditText**


P.S. i tried including the Android SDK files in combinedTypeSolver but that did not help either.

**Comment by ftomassetti** [comment]
I guess what is happening is that is not finding the JAR containing that class. I am not sure why is that happening

**Comment by tamtam22** [comment]
Sorry for the troubles! I'm happy to solve most of the problem. Now only 1 problem remaining!

I can't seem to solve the following MethodCallExpr (the other Android methods are all OK except this one):
Method: `setContentView`
Code: `setContentView(R.layout.activity_main)`

I have checked Android SDK under "android\app\Activity.java" and the method does exists there.

Stack trace is:
~~~~
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: setContentView(R.layout.activity_main), Parameter: R.layout.activity_main
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:220)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:235)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:143)
	at com.myproject.test.utils.TypeSolver.getType(TypeSolver.java:20)
	at com.myproject.test.checkers.MisconfigurationChecker$1.visit(MisconfigurationChecker.java:65)
	at com.myproject.test.checkers.MisconfigurationChecker$1.visit(MisconfigurationChecker.java:46)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:98)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:340)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:64)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:123)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:66)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:487)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:179)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:119)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:210)
	at com.myproject.test.checkers.MisconfigurationChecker.lambda$check$0(MisconfigurationChecker.java:74)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at com.myproject.test.checkers.MisconfigurationChecker.check(MisconfigurationChecker.java:45)
	at com.myproject.test.Main.check(Main.java:78)
	at com.myproject.test.Main.main(Main.java:74)
Caused by: UnsolvedSymbolException{context='unknown', name='Field not found: layout', typeSolver=null}
	at com.github.javaparser.symbolsolver.model.declarations.ReferenceTypeDeclaration.getField(ReferenceTypeDeclaration.java:75)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:164)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:34)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:359)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:251)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:245)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.FieldAccessContext.solveSymbolAsValue(FieldAccessContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:66)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:175)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:34)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:359)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:251)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:216)
	... 20 more
~~~~

**Comment by ftomassetti** [comment]
to find a method it first needs to calculate the type of the parameters, because a method could be overloaded. In this case I think the issue is that it is not able to find the field "layout" in the class R.

By the way, can I ask you what you are working on using JavaSymbolSolver?

**Comment by tamtam22** [comment]
Ok yup it couldn't resolve `layout`!

I tried using node.getParentNode.get() and noticed that it is an instance of ExpressionStmt. Since it's not possible to solve the expression, and this is a really rare case (doesn't happen to other Android files), I have  hard-coded this exceptional case to return "android.app.Activity" if its method name = "setContentView".

I believe this is a pretty rare case and beyond what the symbol solver is for, so it can be safely ignored.

P.S. I'm trying to use it to perform static code analysis on Android APKs to better secure them from common vulnerabilities due to poor coding quality.
