### ISSUE TITLE
UnsupportedOperationException when solving an  ArrayAccesExpr node with brackets

### ISSUE THREAD

**Issue by MarcialSanchez** [javaparser/javasymbolsolver#17]
When I try to solve this kind of expression:
    arrSQL[1]

This is what I get

```
java.lang.UnsupportedOperationException: com.github.javaparser.ast.expr.ArrayAccessExpr
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:392)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
    at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
```

**Comment by ftomassetti** [comment]
Thanks for reporting this. Support for arrays is not yet 100% complete, I will work on that.

**Comment by ftomassetti** [comment]
Solved some time ago, added test to verify that
