### ISSUE TITLE
Type inference issue for method arguments

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#183]
Please consider the following code snippet.

```java
public class Base{
	class Derived extends Base{
	}
	
	public void bar(Optional<Base> o) {
	}

	public void foo() {
		bar(Optional.of(new Derived()));
	}
}
```

For this code the JSS is unable to find a declaration for the method call to `bar` because the argument type is solved as Optional<Derived> where Java actually would infer Optional<Base>. At least I think that this causes the issue.

**Comment by loicfortin** [comment]
Hi @mlangkabel 

I tried your problem and couldn't get a declaration for `bar` too.

However, with the code below

```java
import java.util.Optional;

public class Base{
	static class Derived extends Base{
	}
	
	public void bar(Optional<Base> o) {
	}

	public void foo() {
		Optional o = Optional.of(new Derived());
		bar(o);

		Derived d = new Derived();
		bar(Optional.of(d));

		bar(Optional.of(new Derived()));
	}
}
```

the first call of `bar(o)` was solved as `Base.bar(java.util.Optional<Base>)`. The two other calls of `bar` couldn't be solved.

I will try to take a look at this problem in the next weeks (I won't have enough time before :/).

**Comment by staslev** [comment]
+1

I'm seeing similar issues related to type inference, but in a slightly different use-case:

```java

class ComplexGenericArgument {

    static class Items<T> {
        public <Output extends T> Output apply(Transform<? super Items<T>, Output> t) {
            return null;
        }
    }

    static class Transforms {
        public static <I, O> Transform<I, O> of(DoFn<I, O> fn) {
            return null;
        }
    }

    static class Transform<Input, Output> {

    }

    static class DoFn<Input, Output> {

    }

    static class MyFn extends DoFn<Integer, Long> {

    }

    public void main() {
        Items<Integer> items;
        items.apply(Transforms.of(new MyFn())); // this fails to be resolved.
    }

}

```

```
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: items.apply(Transforms.of(new MyFn())), Parameter: Transforms.of(new MyFn())
...
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.matchTypeParameters(MethodCallExprContext.java:404)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.resolveMethodTypeParameters(MethodCallExprContext.java:364)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:92)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:39)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:86)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:240)
```

I believe I have managed to pinpoint the problem and will have a PR shortly. 
I'm afraid I can't tell for sure whether we are being bitten by the same issue.

**Comment by loicfortin** [comment]
Hi @staslev 

Here is the result of my test with your code

```
ComplexGenericArgument.Items.apply(ComplexGenericArgument.Transform<? super ComplexGenericArgument.Items<T>, Output>)
ComplexGenericArgument.Transforms.of(ComplexGenericArgument.DoFn<I, O>)
```

Is this supposed to be the right solution ?

What i've changed is in `MethodCallExprContext#matchTypeParameters`. I added this test case

```java
                if (actualType.asReferenceType().typeParametersValues().size() > 0) {
                    matchTypeParameters(tp, actualType.asReferenceType().typeParametersValues().get(i), matchedTypeParameters);
                }
```

in the 2nd `else if(...)`. But this is just a test i've added after the first call (with the same error than you). I need to do more research to understand what the method is used for, etc.

**Comment by staslev** [comment]
Thanks for testing!

I think the root cause is that `actualType.asReferenceType().typeParametersValues()` comes up empty if it does not have type parameters which may not be ideal for instance, in the following case:
```java
class NonGeneric extends VeryGeneric<Integer> {...}
````

`NonGeneric` will state it has no type arguments, and if a method's signature demands that all the generic type parameters of its argument are fulfilled, it may try to traverse an empty list.

I've been playing around with collecting the generic params from everyone up the inheritance chain, so that such signatures happy.

Hopefully I'll have a PR to showcase what I mean soon enough.

**Edit**: 

@3ch0 , just tried out your suggestion (I'm trying to resolve the `apply` method), and got:

```java
ComplexGenericArgument.Items.apply(ComplexGenericArgument.Transform<? super ComplexGenericArgument.Items<T>, Output>)
```

Which is pretty nice.

I wonder though, isn't that `if` preventing the generic type params from being verified by matching?
That is, it skips the actual matching in case `typeParametersValues` of the concrete type are empty, and will thus not consider the parent's generic arguments (e.g., the `NonGeneric` class example above).

**Comment by loicfortin** [comment]
Yes you're right, the error `IndexOutOfBoundsException` happens when `typeParametersValues()` is empty. Your PR fixed that issue.

Regarding your question, `typeParametersValues` try to match each generic type from `expectedType` with the one in `actualType` but does not consider parent's types. Thus adding the if condition does not change the method behavior (except the exception thrown).
I'm not sure i understood what you meant ^^

**Comment by ftomassetti** [comment]
Regarding the first example, the fact is that we would probably need special support for generic arguments that are inferred:

```
bar(Optional.<Derived>of(new Derived())); // would fail
bar(Optional.of(new Derived())); // would succeed
```

It is like we are postponing taking a decision on the type of `Optional.of(new Derived())` until we consider the context. It seems a tricky one to me.
