### ISSUE TITLE
What this error means and how to solve it?

### ISSUE THREAD

**Issue by leotu** [javaparser/javasymbolsolver#205]
I modified the example code from here:
https://github.com/javaparser/javasymbolsolver/blob/master/java-symbol-solver-examples/src/main/java/com/github/javaparser/examples/PrintExpressionType.java

```java
Exception in thread "main" java.lang.RuntimeException: Error calculating the type of parameter value of method call Objects.requireNonNull(value)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:498)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:255)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:37)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:86)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
```

**Comment by leotu** [comment]
Here are testing codes those only using JDK built-in class.

[Uploading AppVersion.java.txt…]()

**Comment by matozoid** [comment]
@leotu - are you still waiting for the answer?

**Comment by matozoid** [comment]
@ftomassetti - can you retest or close this?
