### ISSUE TITLE
Resolving class of cloned node

### ISSUE THREAD

**Issue by Meddan** [javaparser/javasymbolsolver#210]
When I try and do: 
```
JavaParserFacade.get(combinedTypeSolver).getTypeOfThisIn(n).asReferenceType().getQualifiedName();
```
on a clone of a node I get: 
```
Exception in thread "main" java.lang.NullPointerException
	at com.github.javaparser.symbolsolver.javaparser.Navigator.getParentNode(Navigator.java:44)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeOfThisIn(JavaParserFacade.java:508)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeOfThisIn(JavaParserFacade.java:508)
```

Not sure if I'm trying to do something that is not intended to work, or if this is a bug.

**Comment by Meddan** [comment]
Never mind this seems to be my own fault.
