### ISSUE TITLE
Issue calculating the type of the scope of MethodCallExprContext

### ISSUE THREAD

**Issue by wompers** [javaparser/javasymbolsolver#227]
Hi!

I have a code that looks like this:

```
java.math.BigDecimal Amount = new java.math.BigDecimal("12345");
String strAmount = Amount.setScale(2, java.math.RoundingMode).toString();
```

and my visit implementation looks like this:

```
@Override
public void visit(MethodCallExpr n, JavaParserFacade javaParserFacade) {
	super.visit(n, javaParserFacade);
		String method = "";
		if(n.getScope().isPresent()) {
			try {
				MethodDeclaration methodDeclaration = javaParserFacade.solve(n).getCorrespondingDeclaration();
				method= methodDeclaration.getPackageName() + "." + methodDeclaration.getClassName();
			} catch (Exception e) {
				e.printStackTrace();
			}
		} 
	}
```

However, I am encountering this error:
```
java.lang.RuntimeException: Issue calculating the type of the scope of MethodCallExprContext{wrapped=Amount.setScale(2, java.math.RoundingMode).toString()}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:151)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:261)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:145)

```

How should a code like this be parsed?
Thanks!

**Comment by Lingam8454** [comment]
Any update on this issue?

**Comment by ftomassetti** [comment]
I suspect this has been solved, I would need to write a test to double check that

**Comment by matozoid** [comment]
@Lingam8454 - if you would like to speed this up, you can consider writing a PR with a test.
