### ISSUE TITLE
UnsupportedOperationException when instanciating an anonymous class from an inner class

### ISSUE THREAD

**Issue by Gottox** [javaparser/javasymbolsolver#235]
An UnsupportedOperationException is thrown when resolving ```new Bar.Baz()``` in the example below:

```java
class Foo {
    static class Bar {
        static class Baz {}
    }
    void m() {
        new Bar.Baz() {};
    }
}
```

The corresponding test code:

```java
        ClassOrInterfaceDeclaration cls = Navigator.demandClassOrInterface(cu, "Foo");
        MethodDeclaration m = Navigator.demandMethod(cls, "m");
        ExpressionStmt stmt = (ExpressionStmt) m.getBody().get().getStatements().get(0);
        final ObjectCreationExpr expression = (ObjectCreationExpr) stmt.getExpression();
        TypeSolver typeSolver = new ReflectionTypeSolver();
        JavaParserFacade javaParserFacade = JavaParserFacade.get(typeSolver);
        javaParserFacade.convertToUsage(expression.getType());
```

* This neither happens with `new Bar() {}` nor `new Foo.Bar() {}`
* removing the `{}` to instanciate the class directly works too.

I'm opening a PR with the failing test soon.

**Comment by Gottox** [comment]
stacktrace:
```
java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.model.resolution.SymbolReference.getCorrespondingDeclaration(SymbolReference.java:61)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserAnonymousClassDeclaration.<init>(JavaParserAnonymousClassDeclaration.java:45)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AnonymousClassDeclarationContext.<init>(AnonymousClassDeclarationContext.java:32)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:81)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:418)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:422)
	at com.github.javaparser.symbolsolver.Issue235.issue235(Issue235.java:41)
```
