### ISSUE TITLE
Ambiguous method call exception on parsing Java class

### ISSUE THREAD

**Issue by sivasamyk** [javaparser/javasymbolsolver#239]
I am trying to parse the following Java class with java Symbol Parser:
```java
import java.util.logging.Level;
import java.util.logging.Logger;
public class TestClass {
    private static Logger logger = Logger.getLogger(TestClass.class.getName());
    public static void main(String args[]) {
        logger.log(Level.SEVERE,"This is severe log...");
    }
}
```

The parsing code is 

```java
        File src = new File("/home/user/lab/java_projects/src");
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(new JavaParserTypeSolver(src));
        SourceFileInfoExtractor sourceFileInfoExtractor = new SourceFileInfoExtractor();
        sourceFileInfoExtractor.setTypeSolver(combinedTypeSolver);
        sourceFileInfoExtractor.solve(src);
```
I am getting following exception, when symbolsolver is trying to resolve logger.log() method call (its getting confused between Logger.log(Level,String) and Logger.log(Level,Supplier<String>)):

```
Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public void java.util.logging.Logger.log(java.util.logging.Level,java.lang.String)}, paramTypes=[ReferenceType{java.util.logging.Level, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public void java.util.logging.Logger.log(java.util.logging.Level,java.util.function.Supplier)}, paramTypes=[ReferenceType{java.util.logging.Level, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.util.function.Supplier, typeParametersMap=TypeParametersMap{nameToValue={java.util.function.Supplier.T=ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}]}. First declared in java.util.logging.Logger

Exception in thread "main" com.github.javaparser.symbolsolver.model.declarations.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public void java.util.logging.Logger.log(java.util.logging.Level,java.lang.String)}, paramTypes=[ReferenceType{java.util.logging.Level, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public void java.util.logging.Logger.log(java.util.logging.Level,java.util.function.Supplier)}, paramTypes=[ReferenceType{java.util.logging.Level, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.util.function.Supplier, typeParametersMap=TypeParametersMap{nameToValue={java.util.function.Supplier.T=ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}]}. First declared in java.util.logging.Logger
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicableUsage(MethodResolutionLogic.java:543)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.solveMethodAsUsage(ReflectionClassDeclaration.java:197)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:56)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:211)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:434)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:116)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:39)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:98)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.SourceFileInfoExtractor.solve(SourceFileInfoExtractor.java:122)
	at com.github.javaparser.symbolsolver.SourceFileInfoExtractor.lambda$solve$2(SourceFileInfoExtractor.java:191)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.javaparser.symbolsolver.SourceFileInfoExtractor.solve(SourceFileInfoExtractor.java:191)
	at com.github.javaparser.symbolsolver.SourceFileInfoExtractor.solve(SourceFileInfoExtractor.java:182)
	at com.github.javaparser.examples.ProjectResolver.main(ProjectResolver.java:38)
`

**Comment by sivasamyk** [comment]
Changing  `sourceFileInfoExtractor.solve(src);` with ` sourceFileInfoExtractor.solveMethodCalls(src);` solved the issue
