### ISSUE TITLE
Problem solving method call "System.out.println()"

### ISSUE THREAD

**Issue by lodart** [javaparser/javasymbolsolver#245]
Hi ! I'm going to need to use JavaParser and JSS for a project for an Internship, and I'm a bit struggling with the TypeSolver. I tried to adapt the piece of code from the JavaParserVisited pdf to Test classes and ended with this error when `System.out.println()` was present on one of my parsed files : 

> Exception in thread "main" java.lang.NoSuchMethodError: com.github.javaparser.ast.expr.FieldAccessExpr.getScope()Ljava/util/Optional;

Here's how I built my CombindeTypeSolver : 

        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(srcDir));
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(javaParserTypeSolver);

I thought this would be covered by the ReflectionTypeSolver, as  `System.out.println()` is part of the Language (right ?) but it is not.

**Comment by lodart** [comment]
Well, I don't know what I did wrong, but now it seems to work.

**Comment by lodart** [comment]
Never mind, I'm confused :/

**Comment by ftomassetti** [comment]
Could you provide more details, like the whole code you were using, the files you were trying to parse, etc.?

**Comment by matozoid** [comment]
It's a javaparser.jar/java-symbol-solver.jar version mismatch again. Please remove the javaparser dependency from you pom.xml.

**Comment by lodart** [comment]
@matozoid @ftomassetti  My bad, I was juggling between projects and didn't realise this one was on 0.5.1 (I had only one java-symbol-solver-core dependency, though).
Changed it to 0.5.5, and now it works.
In the meantime, I tried parsing source code of larger projects ([https://github.com/SilenceIM/Silence](https://github.com/SilenceIM/Silence) for instance), but I've got a lot of unsolved Method Calls (about 75%)
Here is how it looks like : 
```java
SourceRoot sourceRoot = new SourceRoot(Paths.get(CODE_ROOT));
sourceRoot.tryToParse();
List<CompilationUnit> listCus = sourceRoot.getCompilationUnits();

for (CompilationUnit cu:listCus
        ) {
    List<MethodCallExpr> mcs = Navigator.findAllNodesOfGivenClass(cu,MethodCallExpr.class);
    mcs.forEach(mc->{
        try{
            String method = JavaParserFacade.get(solver).solve(mc).getCorrespondingDeclaration().getQualifiedSignature();
            System.out.println(method);
        }catch(Exception e){solveErrorCounter++;}
    });
}
```
And Here is how my solver looks like : 
```java
private static final CombinedTypeSolver solver =new CombinedTypeSolver(
            new JavaParserTypeSolver(new File(LIBS_ROOT)),
            new JavaParserTypeSolver(new File(CODE_ROOT)),
            new ReflectionTypeSolver()
    );
```
Sorry, my questions might be trivials but I'm having trouble going forward on my internship project :/
The idea is to parse Android source code from apks and see where Network Methods are used.

**Comment by ftomassetti** [comment]
please note that if your are using libraries (like the Android libraries) you need to add the corresponding JarTypeSolver otherwise method resolution will fail

**Comment by lodart** [comment]
Thank you ! That helped, but now it seems like I'm stuck in an infinite loop after solving some method calls : 
```
Exception in thread "main" java.lang.StackOverflowError
	at javassist.bytecode.SignatureAttribute.parseTypeParams(SignatureAttribute.java:1060)
	at javassist.bytecode.SignatureAttribute.parseSig(SignatureAttribute.java:991)
	at javassist.bytecode.SignatureAttribute.toClassSignature(SignatureAttribute.java:924)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistTypeDeclarationAdapter.getTypeParameters(JavassistTypeDeclarationAdapter.java:74)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.getTypeParameters(JavassistClassDeclaration.java:331)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceType.deriveParams(ReferenceType.java:451)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceType.<init>(ReferenceType.java:52)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:57)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:264)
	at com.github.javaparser.symbolsolver.model.declarations.ReferenceTypeDeclaration.canBeAssignedTo(ReferenceTypeDeclaration.java:175)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:224)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:264)
	at com.github.javaparser.symbolsolver.model.declarations.ReferenceTypeDeclaration.canBeAssignedTo(ReferenceTypeDeclaration.java:175)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:224)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:264)
	at com.github.javaparser.symbolsolver.model.declarations.ReferenceTypeDeclaration.canBeAssignedTo(ReferenceTypeDeclaration.java:175)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
... and so on, and so on...
```
