### ISSUE TITLE
Generic interface into a jar throws RuntimeException

### ISSUE THREAD

**Issue by olliveirallucas** [javaparser/javasymbolsolver#257]
Hello,

I'm using javasymbolsolver to interpret a complex java code and I guess that I found a bug.
The bug occurs when I try to get the type returned by a method call of an interface contained in a jar file.
Here is part of the stack trace error:
```
java.lang.RuntimeException: javassist.bytecode.SignatureAttribute.TypeVariable
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.signatureTypeToType(JavassistUtils.java:133)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.getParam(JavassistMethodDeclaration.java:124)
	at com.github.javaparser.symbolsolver.model.methods.MethodUsage.<init>(MethodUsage.java:44)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.getMethodUsage(JavassistUtils.java:49)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistInterfaceDeclaration.solveMethodAsUsage(JavassistInterfaceDeclaration.java:101)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:52)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:211)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:434)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:116)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:39)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:99)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
...
```

A minimal example to trigger the error is given below. Consider the java files:

**com/testbug/A.java**
```
package com.testbug;
import net.testbug.B;
public class A {
	private B obj;
	public void run()
	{
		obj.setParameter(null);
	}	
}
```

**net/testbug/B.java**
```
package net.testbug;
public interface B <T>
{
	<T> void setParameter(T value);
}
```

Complile the interface net.testbug.B and generate a jar file with only this interface.
Now, if you try to get the type returned by the call "obj.setParameter(null)" in the class A,
using JarTypeSolver to import the jar with interface B, the result will the
java.lang.RuntimeException: javassist.bytecode.SignatureAttribute.TypeVariable.

Can you conffirm if it is a bug ?

Regards,
Lucas

**Comment by ftomassetti** [comment]
Hi Lucas, yes, it sounds like a bug. Thanks for reporting it.
