### ISSUE TITLE
Error solving field declarations inherited from interfaces

### ISSUE THREAD

**Issue by rbarbudo** [javaparser/javasymbolsolver#314]
As pointed in https://stackoverflow.com/questions/1513520/why-are-all-fields-in-an-interface-implicitly-static-and-final, interfaces can declare fields which can be inherited by the classes that implements them. I can't solve these fields with JSS. I think this could be fixed in class `com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor` if `hasField` looks for the fields inherited not only by a `extends` relation
```
    private Type solveDotExpressionType(ReferenceTypeDeclaration parentType, FieldAccessExpr node) {
        // Fields and internal type declarations cannot have the same name.
        // Thus, these checks will always be mutually exclusive.
        if (parentType.hasField(node.getName().getId())) {
            return parentType.getField(node.getName().getId()).getType();
        } else if (parentType.hasInternalType(node.getName().getId())) {
            return new ReferenceTypeImpl(parentType.getInternalType(node.getName().getId()), typeSolver);
        } else {
            throw new UnsolvedSymbolException(node.getName().getId());
        }
    }
```

**Comment by rbarbudo** [comment]
I think I have solved the issue. I modified the `private void collectDeclaredFields(CtClass ctClass, List<FieldDeclaration> fieldDecls)` from `JavassistTypeDeclarationAdapter`.'The idea is not to check only the superclass but also the interfaces declared:
```
  private void collectDeclaredFields(CtClass ctClass, List<FieldDeclaration> fieldDecls) {
    if (ctClass != null) {
      Arrays.stream(ctClass.getDeclaredFields())
          .forEach(f -> fieldDecls.add(new JavassistFieldDeclaration(f, typeSolver)));
      try {
    	for(CtClass iface: ctClass.getInterfaces())
          collectDeclaredFields(iface, fieldDecls);
        collectDeclaredFields(ctClass.getSuperclass(), fieldDecls);
      } catch (NotFoundException e) {
        // We'll stop here
      }
    }
  }

**Comment by BenWilsonI** [comment]
On https://github.com/javaparser/javasymbolsolver/blob/master/java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typesolvers/JavaParserTypeSolver.java it says in declaration of 
public SymbolReference<ReferenceTypeDeclaration> tryToSolveType(String name) 

        // TODO support enums
        // TODO support interfaces

Is this issue solving these TODOs?

**Comment by ftomassetti** [comment]
At least partially: the part on interfaces. We should take care also of enums

**Comment by ftomassetti** [comment]
We will work on this as we finish another big change. If we get a PR in the meantime it would be welcome

**Comment by ftomassetti** [comment]
It seems to work for me, adding a test to verify this, committing the test and closing.
If the issue arise for someone else please reopen it. Also, an example of the failing test would be perfect.

**Comment by virtanAnton** [comment]
Hello! Thanks for your project : )
It seem that interfaces not fully supported or i am not understand something... 
Soler throw exception in this scenario:
When interface B located in the analyzed file, everything works good. But if interface B located as seperate class, solver throws UnsolvedSymbolException

```
package team.dudes.sample;

public class Example {
    private A a;

    public void cll() {
        a.foo();
    }

    public interface A extends B {
        void foo();
    }
}
```

```
package team.dudes.sample;
public interface B {
    boolean bar();
}
```

Unsolved symbol : B
UnsolvedSymbolException{context='unknown', name='B', typeSolver=null}
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.toReferenceType(JavaParserInterfaceDeclaration.java:325)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.getAncestors(JavaParserInterfaceDeclaration.java:257)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:95)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:605)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:190)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:255)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:138)
	at team.dudes.lumly.uml.analyzer.core.extractor.MethodBodyCallExtractor.visit(MethodBodyCallExtractor.java:26)
	at team.dudes.lumly.uml.analyzer.core.extractor.MethodBodyCallExtractor.visit(MethodBodyCallExtractor.java:17)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:76)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$98(VoidVisitorAdapter.java:410)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:118)
	at team.dudes.lumly.uml.analyzer.core.extractor.MethodDeclarationExtractor.visit(MethodDeclarationExtractor.java:33)
	at team.dudes.lumly.uml.analyzer.core.extractor.MethodDeclarationExtractor.visit(MethodDeclarationExtractor.java:15)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:118)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:104)
	at team.dudes.lumly.uml.analyzer.core.extractor.ClassOrInterfaceExtractor.visit(ClassOrInterfaceExtractor.java:53)
	at team.dudes.lumly.uml.analyzer.core.extractor.ClassOrInterfaceExtractor.visit(ClassOrInterfaceExtractor.java:17)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:104)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
	at team.dudes.lumly.uml.analyzer.core.Analyzer.analyzeFile(Analyzer.java:32)
	at team.dudes.lumly.uml.analyzer.core.AnalyzerTest.analyzeExample(AnalyzerTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
