### ISSUE TITLE
[Question] find all method calls of specified type

### ISSUE THREAD

**Issue by AndrewAQ** [javaparser/javasymbolsolver#333]
Hello everyone! 
I was trying to findout is it possible to find all method calls for specified type, but I met a problem.
I have code like this: 
```
public class Test {
`   public void run(MyClass myclass) {
        myclass.doSomething();
    }
}
```
And what I want is to get all calls of doSomething method of MyClass and change this calls to `myclass.firstdothis().doSomething();`
I am init type solver like this
` typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), JarTypeSolver.getJarTypeSolver(pathToMyClassJarFile));`

and then I trying to solve it with example that I got from book
```
  List<MethodCallExpr> methodCalls= Navigator.findAllNodesOfGivenClass(compilationUnit, MethodCallExpr.class);

        for (MethodCallExpr methodDeclaration:fieldDeclaration) {
        System.out.println(JavaParserFacade.get(typeSolver).solve(methodDeclaration).getCorrespondingDeclaration().getQualifiedSignature())
        }
```
But I`ve got such exception:
```
java.lang.RuntimeException: javassist.NotFoundException: org.eclipse.jetty.util.component.AbstractLifeCycle
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethod(JavassistClassDeclaration.java:193)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:614)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:196)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:258)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:142)`
```
It would be great if somebody could help me to find out what  am I missing, thanks.

**Comment by ftomassetti** [comment]
The problem seems that your library is using a dependency (jetty) and it is not listed into the TypeSolver initialization, so JSS does not know where to find it

**Comment by ftomassetti** [comment]
No feedback, closing. Please reopen if you have still the issue
