### ISSUE TITLE
CompilationUnitContext.solveType() doesn't handle enum declaration in same C.U.

### ISSUE THREAD

**Issue by esstrifork** [javaparser/javasymbolsolver#347]
In this method, only `ClassOrInterfaceDeclaration` and `AnnotationDeclaration` are handled when present in the same compilation unit.

Example stacktrace:
```
java.lang.UnsupportedOperationException: com.github.javaparser.ast.body.EnumDeclaration
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:122)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:83)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:435)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:483)
```

**Comment by ftomassetti** [comment]
Thank you for reporting this issue, I am working on a solution

**Comment by esstrifork** [comment]
That was quick! Didn't expect a fix so soon - thanks!

**Comment by ftomassetti** [comment]
Thank you, we hope to get a release in 1-2 weeks
