### ISSUE TITLE
Unable to get types for java common classes

### ISSUE THREAD

**Issue by fvanham** [javaparser/javasymbolsolver#365]
I'm unable to get the types for java's common built-in classes, but I cannot figure out where my code is off. Using Symbolsolver 0.6.3:
```java
public class MathTest {
	public static void main(String[] args) throws FileNotFoundException {
		// set up combined type solver
        CombinedTypeSolver ts = new CombinedTypeSolver();
        ts.add( new ReflectionTypeSolver() );
        ts.add( new JavaParserTypeSolver(new File("./sample") ) );
        // parse to CompilationUnit
        CompilationUnit cu = JavaParser.parse(new File("./sample/Test.java"));
        cu.accept(
            new VoidVisitorAdapter<Void>() {
            	// visit all named expressions
                public void visit( NameExpr n, Void v ) {
                	try
                	{
                		// attempt to get type
                		ResolvedType type = JavaParserFacade.get( ts ).getType( n );
                		System.out.println( n + ":" + type.describe() );
                	}
                	catch ( Exception e )
                	{
                 		e.printStackTrace();
                	}
                	super.visit( n, v );
                }
            },
        null );
    }
}
```
which parses this file content
```java
public class Test {
	public static void main( String[] args )
	{
		System.out.println( Math.round( Math.random() * Integer.parseInt( args[0] ) ) );
	}
}
```
The result is two failed type resolutions on `Math`, one on `System` and one on `Integer`. I'm a bit surprised the typesolver is null in the TypeExtractor.
```
UnsolvedSymbolException{context='Solving Math', name='Math', typeSolver=null}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:290)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:388)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at MathTest$1.visit(MathTest.java:33)
	at MathTest$1.visit(MathTest.java:1)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:84)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$94(VoidVisitorAdapter.java:402)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$80.00000000039BD2F0.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:402)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:104)
	at com.github.javaparser.ast.expr.BinaryExpr.accept(BinaryExpr.java:98)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$78.00000000039BC990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$78.00000000039BC990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:76)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$77.00000000039BC4E0.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$98(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$76.00000000039BC030.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:118)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$75.00000000039BBB80.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:104)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$71.00000000055F7990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
	at MathTest.main(MathTest.java:26)
```

Running this in Eclipse with IBM J9 JRE, but Sun's Java JRE gives the same result. Since `args` resolves correctly, I'm assuming I've set things up in the right way. What am I missing?

**Comment by bennewi** [comment]
I think the problem is that Math System and Integer aren't symbols, they are classes. If you try your test again but as input use non-static references to objects you'll get some results.

**Comment by fvanham** [comment]
`Math`, `System` and `Integer` are static classes by design. There is only ever a singleton instance of these, referenced by `Math`. I don't think I can create non-static instances of these. I was expecting ReferenceTypes `java.lang.Math`, `java.lang.System` and `java.lang.Integer` as results. Named references to (non-java native) classNames resolve fine.

**Comment by fvanham** [comment]
Here's an even simpler example which fails
```java
public class Test {
	public static void main( String[] args )
	{
		Test.method();
	}
	
	public static void method()
	{
		System.err.println( "Fail" );
	}
}
```
I would expect the type of `Test` in `Test.method()` to be `Test`, since it's a direct reference to a type. Seems like a problem with statics?

**Comment by ftomassetti** [comment]
I think the static method or the static field should be resolved, regarding the name of the class, this is slightly more complicated.

Is the call `Test.method()` resolved?
Is the field access `System.err` resolved?

I would consider wrong to say that `Test` has type `Test`, because that would be the type of an _instance_ of Test. Note that you can instantiate Test:

```
Test instance = new Test();
```

Now, I would consider wrong to say that `instance` and `Test` are thing with the same type, they are not. I can understand you want a way to get what `Test` is, and we could add API for that. JSS should get the information correctly because it can solve static methods calls

**Comment by fvanham** [comment]
Yes JSS gets the types for fields and methods correctly
```
System.err.println("Test1") : void
System.err : java.io.PrintStream
```
I think the issue comes from `System` in `System.out.println()` being designated as `NameExpr` by the parser (not that I could see how it could infer anything else), but when asked for the type of that NameExpr by the solver it throws an exception. If `System` is not of type `java.lang.System`, should it be of type `java.lang.Class<java.lang.System>`? In other words should`ReferenceType` have another subclass  `ClassType`?

**Comment by bennewi** [comment]
I agree with Federico here; You can write 

```
//Test.java
package com.whatever;
public class Test {}

// NotATest.java
package com.whatever;
public class NotATest {
  static void peep()
    {}
}

// Main.java
package com.whatever;
public class Main {
  public static void main(String[] args) {
    NotATest.peep();
    Test NotATest = new Test();
    NotATest.peep();
  }
}
```

and this should fail compilation, not succeed, because the peep() method is not in type `Test` (it won't fail on the first line of main, or the second, but the third). So in the case of statics we need to disambiguate between classes and symbols.
