### ISSUE TITLE
NoClassDefFoundError while trying to create a JarTypeSolver

### ISSUE THREAD

**Issue by urielSilva** [javaparser/javasymbolsolver#371]
I'm getting a `NoClassDefFoundError` while trying to create a `JarTypeSolver`. 

Code:
```
try {
     JarTypeSolver jarTypeSolver = new JarTypeSolver("/Users/uriel/Documents/Projetos/mavenproject/dependencies/junit-3.8.1.jar");
} catch (IOException e) {
     e.printStackTrace();
}
```

Stack trace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javassist/NotFoundException
	at com.rascaljava.RascalJavaInterface.main(RascalJavaInterface.java:106)
Caused by: java.lang.ClassNotFoundException: javassist.NotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

Not really sure what's causing this issue.

**Comment by matozoid** [comment]
Hi! I'd guess this is a case of a missing library on your side? You can take a look at this sample setup: https://github.com/javaparser/javasymbolsolver-maven-sample 

If there is something more sinister going on, it would be good to see your project setup.

**Comment by urielSilva** [comment]
Hi, indeed there were some libraries missing. I'm not using Maven currently due to some setup restrictions, but I added the JAR dependencies and it worked. Thanks

**Comment by matozoid** [comment]
Cool, good luck!
