### ISSUE TITLE
SymbolSolver is unable to find inheritanced interface type 

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javasymbolsolver#377]
Hello,

i am trying to find the fully qualified name of interface `main.MyInterface<E>` that is being implemented in class `main.MyClass<E>`.

```
package main;
public class MyClass<E> implements MyInterface<E> { }
```

```
package main;

public class MyInterface<E> { }
```

```
for (ClassOrInterfaceType type : classDeclaration.getImplementedTypes()) {
	ResolvedReferenceType rrt = type.resolve();
	if (rrt != null) {
		String interfaceName = rrt.getQualifiedName();
		if (interfaceName != null) {
			implementedInterfaces.add(new ClassNameInfo(interfaceName));
		}
	}
}
```

Sadly, this yields me an exception:

```
Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$5(Node.java:682)
	at java.base/java.util.Optional.map(Optional.java:254)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:679)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:292)
```

I just updated to the 3.7.1  (from 3.6.23) and now the exception is:

```
java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
	at com.github.javaparser.ast.Node.getData(Node.java:457)
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$5(Node.java:699)
	at java.base/java.util.Optional.map(Optional.java:254)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:698)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:292)
```

I am setting a SymbolSolver before I start running `.resolve()`:

```
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(finalTypeSolver);
JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);
```

I also double checked without the generic types and it always yields the same exception.
Am I doing something wrong or why does this not work as intended?

**Comment by un0btanium** [comment]
Wrong repo... wops

**Comment by matozoid** [comment]
Would you like me to move this issue? There's a new option in github and I'd like to try it :-D

**Comment by un0btanium** [comment]
Oh, thanks, no its fine, I already posted a similar [issue ](https://github.com/javaparser/javaparser/issues/1943#issuecomment-443460476)in the JavaParser repo. It would exist twice then.

edit: Ah you found it already :)
The one in the JavaParser repo is more up-to-date.
edit2: oh well, now I referenced it because I linked it >_<
