### ISSUE TITLE
UnsolvedSymbolException when solving call to UnsupportedOperationException.getMessage()

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#42]
To reproduce override the following method of the VoidVisitorAdapter<Void>:

```
public void visit(final MethodCallExpr n, final Void v) {
    JavaParserFacade.get(new JreTypeSolver()).solveMethodAsUsage(n);
    super.visit(n, v);
}
```

Additionally I added a visit method on `ClassOrInterfaceType` to evaluate if other content of the `java.lang` package is resolved correctly (and this works fine).

```
public void visit(final ClassOrInterfaceType n, final Void v) {
            TypeUsage typeUsage = JavaParserFacade.get(new JreTypeSolver()).convert(n, n);
            me.tomassetti.symbolsolver.model.declarations.TypeDeclaration td = typeUsage.asReferenceTypeUsage().getTypeDeclaration();
            System.out.println(td.getQualifiedName());
            super.visit(n, v);
        }
```

Using this visitor try to parse the following code and visit the resulting compilation unit:

```
public class Bla {
    public void main()
    {
        try
        {
            int i = 0;
        }
        catch (UnsupportedOperationException e)
        {
            String s;
            e.getMessage();
        }
    }
}
```

This results in an `UnsolvedSymbolException` with the following callstack:

```
Exception in thread "main" UnsolvedSymbolException{context='FOO Solving e', name='e', typeSolver=null}
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:213)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
        at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:156)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:496)
        at test.Main$JavaAstVisitor.visit(Main.java:24)
        at test.Main$JavaAstVisitor.visit(Main.java:22)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:399)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
        at com.github.javaparser.ast.stmt.CatchClause.accept(CatchClause.java:66)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:743)
        at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:72)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:562)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:111)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:223)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:85)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:251)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:84)
        at test.Main.main(Main.java:45)
```

**Comment by ftomassetti** [comment]
Good news is that it seems to work fine now. Added a test to prevent possible regressions.
