### ISSUE TITLE
Unable to solve Type defined in base class

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#47]
It seems like the symbol solver is unable to solve a type that has been defined in a class' base class. Please refer to the following code snippet for an example:

```
public class Foo {
    public class Base {
        public class X {
        }
    }

    public class Derived extends Base {
        public X x = null;
    }
}
```

When trying to solve the type of `Derived.x` an `UnsolvedSymbolException{context='unknown', name='X', typeSolver=null}` is thrown (callstack is at the end).

I think the `me.tomassetti.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveType(...)` is missing to look into extended or implemented classes/interfaces.

And here the callstack (it's not very spectacular):

```
Exception in thread "Thread-0" UnsolvedSymbolException{context='unknown', name='X', typeSolver=null}
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:444)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:487)

        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:483)

        at io.coati.JavaTypeNameResolver.getTypeName(JavaTypeNameResolver.java:48)
        ...
```

**Comment by ftomassetti** [comment]
This bug is still present.
